const root=document.documentElement,themeButton=document.querySelector('.theme-toggle'),themeIcon=document.querySelector('.theme-icon');
const savedTheme=localStorage.getItem('portfolio-theme');if(savedTheme)root.dataset.theme=savedTheme;
function updateThemeIcon(){themeIcon.textContent=root.dataset.theme==='dark'?'☀':'☾'}updateThemeIcon();
themeButton.addEventListener('click',()=>{root.dataset.theme=root.dataset.theme==='dark'?'light':'dark';localStorage.setItem('portfolio-theme',root.dataset.theme);updateThemeIcon()});

const navToggle=document.querySelector('.nav-toggle'),navLinks=document.querySelector('.nav-links');
navToggle.addEventListener('click',()=>{const open=navLinks.classList.toggle('open');navToggle.setAttribute('aria-expanded',open)});
document.querySelectorAll('.nav-links a').forEach(link=>link.addEventListener('click',()=>{navLinks.classList.remove('open');navToggle.setAttribute('aria-expanded','false')}));

const revealObserver=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('visible');revealObserver.unobserve(entry.target)}}),{threshold:.12});document.querySelectorAll('.reveal').forEach(el=>revealObserver.observe(el));
const sections=[...document.querySelectorAll('main section[id]')],navAnchors=[...document.querySelectorAll('.nav-links a')];
const sectionObserver=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){navAnchors.forEach(a=>a.classList.toggle('active',a.getAttribute('href')==='#'+entry.target.id))}}),{rootMargin:'-35% 0px -55%'});sections.forEach(s=>sectionObserver.observe(s));

const progress=document.querySelector('.scroll-progress'),backTop=document.querySelector('.back-top');
function onScroll(){const max=document.documentElement.scrollHeight-innerHeight;progress.style.width=(scrollY/max*100)+'%';backTop.classList.toggle('visible',scrollY>600)}addEventListener('scroll',onScroll,{passive:true});backTop.addEventListener('click',()=>scrollTo({top:0,behavior:'smooth'}));

document.querySelectorAll('.filters button').forEach(btn=>btn.addEventListener('click',()=>{document.querySelector('.filters .active').classList.remove('active');btn.classList.add('active');const filter=btn.dataset.filter;document.querySelectorAll('.project-card').forEach(card=>card.classList.toggle('hidden',filter!=='all'&&!card.dataset.category.split(' ').includes(filter)))}));

const projects={unisync:{title:'UNI SYNC Email System',summary:'ระบบเว็บสำหรับจัดการอีเมล พัฒนาด้วย ASP.NET Core Razor Pages โดยมีหน้าจอสำหรับเริ่มต้นใช้งาน สมัครสมาชิก เข้าสู่ระบบ เขียนอีเมล และดูอีเมล',role:'รับผิดชอบการพัฒนาส่วน Frontend ออกแบบโครงสร้างหน้า จัดวางองค์ประกอบ และปรับรูปแบบการแสดงผลของหน้าจอหลัก',tools:'ASP.NET Core Razor Pages, HTML, CSS, Bootstrap',highlights:['พัฒนาหน้า Home และลำดับการเข้าสู่ระบบ','จัดทำหน้า Login และ Register','สร้างส่วนติดต่อผู้ใช้สำหรับเขียนและดูอีเมล','ปรับธีม สี พื้นหลัง และองค์ประกอบด้วย CSS และ Bootstrap'],links:'<a href="https://github.com/pondzyy/unisync-email-system" target="_blank" rel="noopener noreferrer">ดู Source Code บน GitHub ↗</a>'},portfolio:{title:'Secure Portfolio',summary:'เว็บไซต์ Portfolio หน้าเดียวที่ responsive และใช้งานได้โดยไม่ต้องมี framework พร้อม interaction ที่ครบถ้วน',role:'ออกแบบ UI พัฒนา และทดสอบบนขนาดหน้าจอหลายแบบ',tools:'HTML5, CSS3, Vanilla JavaScript',highlights:['Dark / Light mode บันทึกค่าใน browser','Project filter, modal และ certificate lightbox','Semantic HTML, keyboard-friendly dialog และ reduced dependencies'],links:'แทนที่ด้วย GitHub Pages หรือ URL ที่ deploy แล้ว'}};
Object.assign(projects.unisync,{image:'assets/projects/unisync-login.png'});
Object.assign(projects.portfolio,{image:'assets/projects/secure-portfolio-home.png'});
projects.powerbi={title:'Superstore Power BI Dashboard',image:'assets/projects/powerbi-superstore-dashboard.png',summary:'โครงงานกลุ่มสำหรับนำเสนอและสรุปข้อมูลยอดขายและกำไรจากชุดข้อมูล Superstore ผ่าน Dashboard ใน Microsoft Power BI',role:'เป็นนักแสดงในสื่อการนำเสนอของโครงงาน และช่วยตรวจทานเนื้อหารายงานของทีม',tools:'Microsoft Power BI, Data Visualization, Presentation, Report Review',highlights:['ร่วมแสดงในสื่อการนำเสนอผลงานของทีม','ช่วยตรวจทานเนื้อหาและความเรียบร้อยของรายงาน','ร่วมตรวจสอบความสอดคล้องระหว่างรายงานกับ Dashboard'],links:'ผลงานรายวิชาแบบกลุ่ม'};
projects.wpwn={title:'WPWN Vulnerability Assessment',image:'assets/projects/wpwn-vulnerability-assessment.png',summary:'โครงงานประเมินช่องโหว่ของระบบ WPWN ภายใต้ขอบเขตที่ได้รับมอบหมาย พร้อมจัดทำหลักฐาน ผลการตรวจสอบ และข้อเสนอแนะในการแก้ไข',role:'รับผิดชอบทดสอบช่องโหว่ WPWN บันทึกหลักฐานและผลการตรวจสอบ พร้อมเสนอแนวทางแก้ไขโดยอ้างอิงแนวปฏิบัติของ OWASP',tools:'Nessus, OWASP, CVSS, Vulnerability Assessment, Security Documentation',highlights:['ดำเนินการสแกนและตรวจสอบช่องโหว่ตามขอบเขตที่ได้รับอนุญาต','จัดหมวดหมู่และประเมินความรุนแรงของผลการตรวจสอบ','บันทึกหลักฐานและจัดทำรายงานผลอย่างเป็นระบบ','เสนอแนวทางลดความเสี่ยงและแก้ไขโดยอ้างอิง OWASP'],links:'<a href="assets/projects/wpwn-assessment-public-summary.pdf" target="_blank" rel="noopener noreferrer">View Document ↗</a><br><small>ฉบับสรุปสำหรับ Portfolio ซึ่งตัดข้อมูลอ่อนไหวออกแล้ว</small>'};
projects.teenoi={title:'Tee Noi Food Database Design',image:'assets/projects/teenoi-database-report.png',summary:'โครงงานกลุ่มในรายวิชา CS430 Database Systems เรื่องการออกแบบฐานข้อมูลสำหรับระบบจัดการข้อมูลอาหารร้านตี๋น้อย',role:'รับผิดชอบจัดทำรายงาน รวบรวมเนื้อหา และจัดรูปแบบเอกสารของโครงงานกลุ่ม',tools:'Database Design, Report Writing, Documentation, Microsoft Word',highlights:['จัดทำและเรียบเรียงเนื้อหาในรายงาน','จัดโครงสร้างหัวข้อและรูปแบบเอกสาร','ช่วยตรวจทานความถูกต้องและความเรียบร้อยก่อนส่ง'],links:'ผลงานรายวิชาแบบกลุ่ม ภาคเรียนที่ 1 ปีการศึกษา 2568'};
const projectModal=document.querySelector('#project-modal'),modalContent=document.querySelector('#modal-content');
document.querySelectorAll('.project-open').forEach(btn=>btn.addEventListener('click',()=>{const p=projects[btn.dataset.project],toolTags=p.tools.split(',').map(tool=>`<span>${tool.trim()}</span>`).join('');modalContent.innerHTML=`<div class="project-detail-cover">${p.image?`<img src="${p.image}" alt="ภาพตัวอย่าง ${p.title}">`:''}<span>PROJECT DETAIL</span></div><div class="project-detail-content"><header class="project-detail-header"><p class="card-kicker">SELECTED WORK</p><h2>${p.title}</h2><p class="project-detail-summary">${p.summary}</p></header><div class="project-detail-grid"><section><p class="detail-label">MY ROLE</p><h3>ส่วนที่รับผิดชอบ</h3><p>${p.role}</p></section><section><p class="detail-label">TECH STACK</p><h3>เครื่องมือ</h3><div class="project-tool-tags">${toolTags}</div></section><section class="project-highlights"><p class="detail-label">KEY CONTRIBUTIONS</p><h3>ผลงานสำคัญ</h3><ul>${p.highlights.map(x=>`<li>${x}</li>`).join('')}</ul></section></div><aside class="project-note"><strong>หมายเหตุ / ลิงก์</strong><p>${p.links}</p></aside></div>`;projectModal.showModal()}));

const certModal=document.querySelector('#cert-modal'),certFrame=document.querySelector('#cert-frame'),certDownload=document.querySelector('#cert-download');document.querySelectorAll('.cert').forEach(cert=>cert.addEventListener('click',()=>{document.querySelector('#cert-title').textContent=cert.dataset.cert;document.querySelector('#cert-issuer').textContent=cert.dataset.issuer;certFrame.src=cert.dataset.pdf;certDownload.href=cert.dataset.pdf;certModal.showModal()}));
document.querySelectorAll('.modal-close').forEach(btn=>btn.addEventListener('click',()=>{const dialog=btn.closest('dialog');dialog.close();if(dialog===certModal)certFrame.src=''}));document.querySelectorAll('dialog').forEach(dialog=>dialog.addEventListener('click',event=>{if(event.target===dialog){dialog.close();if(dialog===certModal)certFrame.src=''}}));

document.querySelector('#contact-form').addEventListener('submit',event=>{event.preventDefault();const data=new FormData(event.currentTarget),to='you@example.com',subject=encodeURIComponent(data.get('subject')),body=encodeURIComponent(`ชื่อ: ${data.get('name')}\nอีเมล: ${data.get('email')}\n\n${data.get('message')}`);document.querySelector('.form-status').textContent='กำลังเปิดโปรแกรมอีเมล...';location.href=`mailto:${to}?subject=${subject}&body=${body}`});
document.querySelector('#year').textContent=new Date().getFullYear();onScroll();

// ลูกเล่นเสริม: แสงตามเมาส์, navbar เมื่อเลื่อน และมิติของการ์ด
const glow=document.createElement('div');glow.className='cursor-glow';glow.setAttribute('aria-hidden','true');document.body.appendChild(glow);
addEventListener('pointermove',event=>{document.documentElement.style.setProperty('--mouse-x',`${event.clientX}px`);document.documentElement.style.setProperty('--mouse-y',`${event.clientY}px`)},{passive:true});
const header=document.querySelector('.site-header');addEventListener('scroll',()=>header.classList.toggle('scrolled',scrollY>24),{passive:true});header.classList.toggle('scrolled',scrollY>24);
document.querySelectorAll('.project-card,.skill-card,.cert').forEach(card=>card.addEventListener('pointermove',event=>{const box=card.getBoundingClientRect();card.style.setProperty('--card-x',`${event.clientX-box.left}px`);card.style.setProperty('--card-y',`${event.clientY-box.top}px`)}));
const tiltCard=document.querySelector('.identity-card');if(tiltCard&&matchMedia('(pointer:fine)').matches&&!matchMedia('(prefers-reduced-motion:reduce)').matches){tiltCard.addEventListener('pointermove',event=>{const box=tiltCard.getBoundingClientRect(),x=(event.clientX-box.left)/box.width-.5,y=(event.clientY-box.top)/box.height-.5;tiltCard.style.transform=`perspective(900px) rotateX(${-y*7}deg) rotateY(${x*9}deg) translateY(-4px)`});tiltCard.addEventListener('pointerleave',()=>tiltCard.style.transform='rotate(2deg)')}
